### ISSUE TITLE
Toolshed Availability

### ISSUE THREAD

**Issue by CicoZhang** [galaxy-genome-annotation/galaxy-circos-tool#4]
I am very interested in using this tool in Galaxy, will it be available in toolshed? Thank you in advance.

**Comment by CicoZhang** [comment]
Got the answer from another post. Thank you!

**Comment by erasche** [comment]
Re-opening, since it is an issue we need to remember to fix eventually :)

**Comment by rob123king** [comment]
Would be great if in toolshed..I am trying to put it into our own galaxy as a sideline as would be useful. I have it installed on command line but not in path. Can you suggest where to provide hard coded path in wrapper? I need to ask our IT guy to put in bcbiogff too but I'm hoping putting in full path of circos in wrapper in addition to this will do the trick??

**Comment by erasche** [comment]
It is currently on the testtoolshed. No guarantees are made regarding installability or stability yet.

**Comment by erasche** [comment]
It is on the MTS now but @shiltemann and I are rewriting large portions and hope to have a new version soon. Additionally this repo has migrated to the [tools-iuc](https://github.com/galaxyproject/tools-iuc/) repository, you can find future updates there.
